// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC6XrjuRSCownu8ooqdtLKcHH339lJfl-s',
    appId: '1:809081811301:web:3b75f17bdf1e2e1392f18c',
    messagingSenderId: '809081811301',
    projectId: 'arjefojayasentosa',
    authDomain: 'arjefojayasentosa.firebaseapp.com',
    storageBucket: 'arjefojayasentosa.firebasestorage.app',
    measurementId: 'G-F5RW51CPT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD85_otUavTyK5FgoFqLphQcd9_fcm-C0o',
    appId: '1:809081811301:android:6f08f38ff822007e92f18c',
    messagingSenderId: '809081811301',
    projectId: 'arjefojayasentosa',
    storageBucket: 'arjefojayasentosa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpdog-hrYO8Z36sAyEJMH3GeoDbr87MDU',
    appId: '1:809081811301:ios:75e0e7a46b58d98f92f18c',
    messagingSenderId: '809081811301',
    projectId: 'arjefojayasentosa',
    storageBucket: 'arjefojayasentosa.firebasestorage.app',
    iosBundleId: 'com.example.mobileArnold',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpdog-hrYO8Z36sAyEJMH3GeoDbr87MDU',
    appId: '1:809081811301:ios:75e0e7a46b58d98f92f18c',
    messagingSenderId: '809081811301',
    projectId: 'arjefojayasentosa',
    storageBucket: 'arjefojayasentosa.firebasestorage.app',
    iosBundleId: 'com.example.mobileArnold',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC6XrjuRSCownu8ooqdtLKcHH339lJfl-s',
    appId: '1:809081811301:web:48b8ffe8076cde0692f18c',
    messagingSenderId: '809081811301',
    projectId: 'arjefojayasentosa',
    authDomain: 'arjefojayasentosa.firebaseapp.com',
    storageBucket: 'arjefojayasentosa.firebasestorage.app',
    measurementId: 'G-M3FKYHD1EK',
  );

}